id = "rescript"
name = "ReScript"
description = "ReScript support."
version = "0.5.0"
schema_version = 1
authors = ["Karolis Narkevicius <hey@kn8.lt>"]
repository = "https://github.com/sigurthor/rescript-zed"

[language_servers.rescript-language-server]
name = "rescript-language-server"
language = "ReScript"

[grammars.rescript]
repository = "https://github.com/sigurthor/tree-sitter-rescript"
commit = "f81040d23a3c2970e467432178043162acabdd34"
